version: '3'
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/frontend
      - frontend-tmp:/frontend/tmp
      - frontend-node_modules:/frontend/node_modules
      - frontend-cache:/usr/local/share/.cache
    ports:
      - "4200:4200"
      - "35730:35730"
  ws:
    build: ./ws
    volumes:
      - ./ws:/ws
      - ws-cargo:/cargo
    ports:
      - "8000:8000"
volumes:
  frontend-tmp:
  frontend-node_modules:
  frontend-cache:
  ws-cargo:
